version: "3.8"

services:
  flask_stream:
    build: ./flask_app
    container_name: flask_stream
    ports:
      - "8080:8080"
    restart: unless-stopped
    privileged: true   # Raspberry Pi에서 카메라 접근 시 필요
